<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MembershipPlanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('membership_plans')->insert(
            [
                [
                    'name' => '1 day (gym)',
                    'cost' => '0',
                    'validity' => '1',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '1 day (gym+Cardio)',
                    'cost' => '0',
                    'validity' => '1',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '7 days (gym)',
                    'cost' => '0',
                    'validity' => '7',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '7 days (gym+Cardio)',
                    'cost' => '0',
                    'validity' => '7',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '15 days (gym)',
                    'cost' => '0',
                    'validity' => '15',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '15 days (gym+Cardio)',
                    'cost' => '0',
                    'validity' => '15',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '1 month (gym)',
                    'cost' => '0',
                    'validity' => '30',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '1 month (gym+Cardio)',
                    'cost' => '0',
                    'validity' => '30',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '2 months (gym)',
                    'cost' => '0',
                    'validity' => '60',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '2 months (gym+Cardio)',
                    'cost' => '0',
                    'validity' => '60',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '3 months (gym)',
                    'cost' => '0',
                    'validity' => '90',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '3 months (gym+Cardio)',
                    'cost' => '0',
                    'validity' => '90',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '3+1 months (gym)',
                    'cost' => '0',
                    'validity' => '120',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '3+1 months (gym+Cardio)',
                    'cost' => '0',
                    'validity' => '120',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '6 months (gym)',
                    'cost' => '0',
                    'validity' => '180',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '6 months (gym+Cardio)',
                    'cost' => '0',
                    'validity' => '180',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '6+1 months (gym)',
                    'cost' => '0',
                    'validity' => '210',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '6+1 months (gym+Cardio)',
                    'cost' => '0',
                    'validity' => '210',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '6+2 months (gym)',
                    'cost' => '0',
                    'validity' => '240',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '6+2 months (gym+Cardio)',
                    'cost' => '0',
                    'validity' => '240',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '6+3 months (gym)',
                    'cost' => '0',
                    'validity' => '270',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '6+3 months (gym+Cardio)',
                    'cost' => '0',
                    'validity' => '270',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '12 months (gym)',
                    'cost' => '0',
                    'validity' => '365',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '12 months (gym+Cardio)',
                    'cost' => '0',
                    'validity' => '365',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '12+1 months (gym)',
                    'cost' => '0',
                    'validity' => '395',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '12+1 months (gym+Cardio)',
                    'cost' => '0',
                    'validity' => '395',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '12+3 months (gym)',
                    'cost' => '0',
                    'validity' => '455',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '12+3 months (gym+Cardio)',
                    'cost' => '0',
                    'validity' => '455',
                    'created_by' => User::Admin,
                    'updated_by' => User::Admin,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
    }
}
